"use client";

import { useState } from "react";

const colors = [
  ["Primary 500", "#F97316"], ["Primary 400", "#F923C"], ["Primary 300", "#FDBA74"], ["Primary 200", "#FED7AA"], ["Primary 100", "#FFEEE5"],
  ["Neutral 900", "#0F172A"], ["Neutral 700", "#334155"], ["Neutral 500", "#64748B"], ["Neutral 300", "#CBD5E1"], ["Neutral 200", "#E2E8F0"], ["Neutral 100", "#F1F5F9"], ["Neutral 50", "#FAFAFC"], ["White", "#FFFFFF"],
];

function Section({ number, title, children, className = "" }: { number: string; title: string; children: React.ReactNode; className?: string }) {
  return <section className={`sheet-section ${className}`}><div className="section-title"><span>{number}</span><strong>{title}</strong></div>{children}</section>;
}

function Icon({ name, filled = false }: { name: string; filled?: boolean }) {
  const common = { width: 18, height: 18, viewBox: "0 0 24 24", fill: filled ? "currentColor" : "none", stroke: "currentColor", strokeWidth: 1.7, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
  const paths: Record<string, React.ReactNode> = {
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, play: <><circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4z"/></>, file: <><path d="M5 3h10l4 4v14H5z"/><path d="M15 3v5h4M8 13h8M8 17h6"/></>, bookmark: <path d="M6 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18l-6-4-6 4z"/>, chart: <><path d="M5 20V10M12 20V4M19 20v-7"/><path d="M3 20h18"/></>, clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, user: <><circle cx="12" cy="7" r="3"/><path d="M5 21a7 7 0 0 1 14 0"/></>, chevron: <path d="m9 5 7 7-7 7"/>, eye: <><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></>, grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>, target: <><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></>, lock: <><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, accessibility: <><circle cx="12" cy="4" r="2"/><path d="M5 8h14M12 8v12M8 20l4-6 4 6"/></>, external: <><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v6H4V5h6"/></> };
  return <svg {...common}>{paths[name]}</svg>;
}

export default function Home() {
  const [tab, setTab] = useState("Courses");
  const [select, setSelect] = useState("Most Relevant");
  return <main className="page-shell">
    <div className="hero-grid">
      <header className="intro"><div className="brand"><span className="vertex-mark">▼</span><span>Vertex</span></div><h1>Design System</h1><p>A unified design language for Vertex learning platform. Clean, modern and focused on clarity, consistency and intuitive learning experiences.</p><div className="version">VERSION 1.0 <i /> MAY 2025</div></header>
      <Section number="01" title="COLORS" className="colors"><h4>Primary</h4><div className="swatches">{colors.slice(0, 5).map(([name, hex]) => <div className="swatch" key={name}><span style={{ background: hex }} /><label>{name}<small>{hex}</small></label></div>)}</div><h4>Neutral</h4><div className="swatches">{colors.slice(5).map(([name, hex]) => <div className="swatch" key={name}><span style={{ background: hex }} /><label>{name}<small>{hex}</small></label></div>)}</div></Section>
    </div>
    <div className="two-col"><Section number="02" title="TYPOGRAPHY" className="type-show"><div className="type-row"><b className="serif">Ag</b><div><strong>Playfair Display</strong><small>Elegant <em>•</em> Readable <em>•</em> Timeless</small></div></div><div className="type-row"><b>Ag</b><div><strong>Inter</strong><small>Clean <em>•</em> Modern <em>•</em> Highly legible</small></div></div></Section><Section number="03" title="TYPE SCALE" className="scale"><div className="scale-head"><span>Style</span><span>Font</span><span>Size / Line Height</span><span>Weight</span><span>Use</span></div>{[["Display 1","Playfair Display","48 / 56","Bold","Page titles"],["Display 2","Playfair Display","36 / 44","Bold","Section titles"],["Heading 1","Inter","28 / 36","Semi Bold","Card titles"],["Heading 2","Inter","22 / 30","Semi Bold","Sub section"],["Heading 3","Inter","18 / 26","Medium","Small titles"],["Body Large","Inter","16 / 24","Regular","Body copy"],["Body","Inter","14 / 20","Regular","Supporting text"],["Small","Inter","12 / 16","Regular","Captions, meta"]].map(r => <div className="scale-row" key={r[0]}>{r.map((v,i)=><span key={i}>{v}</span>)}</div>)}</Section></div>
    <div className="two-col lower"><Section number="04" title="SPACING SYSTEM"><p className="micro-intro">Base unit: 4px</p><div className="spacing-row">{[[4,"0.25rem"],[8,"0.5rem"],[12,"0.75rem"],[16,"1rem"],[24,"1.5rem"],[32,"2rem"],[40,"2.5rem"],[48,"3rem"],[64,"4rem"]].map(([n, rem]) => <div key={n}><span style={{height: `${Number(n)/2}px`}} /><b>{n}</b><small>({rem})</small></div>)}</div></Section><Section number="05" title="RADIUS & SHADOWS"><div className="radius-row">{[["4px","xs"],["8px","sm"],["12px","md"],["16px","lg"],["24px","xl"],["Full","circle"]].map(([n,l])=><div key={l}><span className={`radius radius-${l}`} /><small>{n}<br/>({l})</small></div>)}</div><div className="shadow-row"><div><b>Sm</b><small>0 1px 2px 0<br/>rgba(15, 23, 42, 0.05)</small></div><div><b>Md</b><small>0 4px 12px -2px<br/>rgba(15, 23, 42, 0.08)</small></div><div><b>Lg</b><small>0 12px 24px -4px<br/>rgba(15, 23, 42, 0.10)</small></div><div><b>Xl</b><small>0 20px 40px -8px<br/>rgba(15, 23, 42, 0.12)</small></div></div></Section></div>
    <div className="three-col"><Section number="06" title="ICONS"><p className="micro-intro">Outline Style</p><div className="icon-row">{["bell","search","play","file","bookmark","chart","clock","user","chevron"].map(n=><Icon key={n} name={n}/>)}</div><p className="micro-intro">Filled Style</p><div className="icon-row filled">{["bell","search","play","file","bookmark","chart","clock","user","chevron"].map(n=><Icon key={n} name={n} filled/>)}</div><ul className="spec-list"><li>24x24px grid</li><li>2px stroke width (outline)</li><li>Rounded line caps</li><li>Consistent optical balance</li></ul></Section><Section number="07" title="BUTTONS" className="buttons"><div className="button-head"><span>Primary</span><span>Secondary</span><span>Tertiary</span><span>Text</span></div>{["Default","Hover","Disabled"].map((state,i)=><div className="button-row" key={state}><span>{state}</span><button className={`primary ${i===2?"disabled":""}`}>Get Started</button><button className={`secondary ${i===2?"disabled":""}`}>Explore Courses</button><button className="tertiary">View Lesson <Icon name="external"/></button><button className="text-button">Watch Video <Icon name="play"/></button></div>)}</Section><Section number="08" title="INPUTS"><label className="field-label">Search / Text Input</label><div className="input"><Icon name="search"/><span>Search anything...</span><kbd>⌘ K</kbd></div><label className="field-label">Select</label><select value={select} onChange={e=>setSelect(e.target.value)}><option>Most Relevant</option><option>Newest First</option><option>Most Popular</option></select><ul className="spec-list"><li>Height: 44px</li><li>Radius: 12px</li><li>Border: 1px solid #E2E8F0</li><li>Padding: 0 16px</li><li>Focus: Border color #F923C</li></ul></Section></div>
    <div className="three-col compact"><Section number="09" title="BADGES / TAGS"><div className="badge-row"><div>Video<span className="badge video">VIDEO</span></div><div>Lesson<span className="badge lesson">LESSON</span></div><div>Popular<span className="badge popular">POPULAR</span></div></div></Section><Section number="10" title="STATUS / INDICATORS"><div className="status-row"><span><i className="status orange"/>In Progress</span><span><i className="status green">✓</i>Completed</span><span><i className="status play-dot">▶</i>Now Playing</span><span><i className="status lock"><Icon name="lock"/></i>Locked</span></div></Section><Section number="11" title="PROGRESS BAR"><div className="progress"><span/><b>35% <small>complete</small></b></div></Section></div>
    <Section number="12" title="CARDS" className="cards"><div className="card-grid"><article><label>Course Card</label><div className="card-content"><div className="next-logo">N</div><div><b>Next.js for Production</b><p>Build scalable, high-performance web applications with Next.js.</p></div></div><div className="card-meta"><span>▥ Intermediate</span><span><Icon name="clock"/> 18h 24m</span><span>□ 12 modules</span></div></article><article><label>Lesson Card (Video)</label><span className="badge video">VIDEO</span><b>Data Fetching in Server Components</b><p>Learn how to fetch data on the server using async/await and Next.js best practices.</p><small>Lesson 5.1 ・ 12:45 <a>◉ Watch from 12:45</a></small></article><article><label>Lesson Card (Lesson)</label><span className="badge lesson">LESSON</span><b>Data Fetching & Caching</b><p>Explore different data fetching methods in Next.js and how to cache and revalidate data for optimal performance.</p><small>Module 5 <a>View lesson ↗</a></small></article><article><label>Resource Card</label><div className="resource"><Icon name="file"/><b>Caching and Revalidation Guide</b></div><p>Deep dive into Next.js caching strategies.</p><small>PDF ・ 1.2 MB <a>↗</a></small></article></div></Section>
    <Section number="13" title="NAVIGATION" className="navigation"><div className="nav-preview"><div className="brand"><span className="vertex-mark">▼</span><span>Vertex</span></div><div className="nav-tabs">{["Courses","My Learning"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="breadcrumbs">All Courses　›　Next.js for Production　›　Data Fetching & Caching</div><div className="pagination">‹　<button>1</button>　2　3　…　8　›</div></div></Section>
    <Section number="14" title="PRINCIPLES" className="principles"><div><Icon name="eye"/><b>Clarity First</b><small>Every element should<br/>communicate clearly.</small></div><div><Icon name="grid"/><b>Consistency</b><small>Use components and patterns<br/>consistently across the platform.</small></div><div><Icon name="target"/><b>Focus & Calm</b><small>Remove noise and help learners<br/>focus on what matters.</small></div><div><Icon name="accessibility"/><b>Accessible</b><small>Design with accessibility<br/>and inclusivity in mind.</small></div></Section>
  </main>;
}
