import Link from 'next/link'
import {notFound} from 'next/navigation'
import {Show, UserButton} from '@clerk/nextjs'
import {PortableText} from '@portabletext/react'
import {getLessonBySlug} from '@/sanity/data'
import {AnalyticsView} from '@/app/analytics-view'
import {LessonVideo} from './lesson-video'
import {LessonBookmark, LessonTabs} from './lesson-ui'

type Item = {_id: string; title: string; slug: {current: string}; duration?: number; freePreview?: boolean}
type Course = {_id: string; title: string; slug: {current: string}; level: string; modules: {_key: string; title: string; summary?: string; lessons: Item[]}[]}
type Lesson = {_id: string; title: string; slug: {current: string}; videoUrl: string; thumbnail?: {alt?: string; [key: string]: unknown}; duration: number; studentCount: number; notes?: unknown[]; keyPoints?: string[]; proTip?: string; resources?: {_key: string; title: string; description?: string; url: string}[]; courses: Course[]}

function duration(seconds: number) {const h = Math.floor(seconds / 3600); const m = Math.round((seconds % 3600) / 60); return h ? `${h}h ${m}m` : `${m}m`}
function Icon({name}: {name: 'bell' | 'clock' | 'level' | 'users' | 'arrow' | 'check'}) {const paths = {bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" /></>, clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3 2" /></>, level: <><path d="M4 20v-4M9 20v-8M14 20v-12M19 20V5" /></>, users: <><circle cx="9" cy="8" r="3" /><path d="M3 20c0-3 2.5-5 6-5s6 2 6 5M16 5.5a3 3 0 0 1 0 5.5M18 15c2.1.5 3 2.1 3 5" /></>, arrow: <><path d="M3 12h17M14 6l6 6-6 6" /></>, check: <><circle cx="12" cy="12" r="9" /><path d="m8 12 2.5 2.5L16 9" /></>}; return <svg className="lesson-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

export default async function LessonPage({params, searchParams}: {params: Promise<{slug: string}>; searchParams: Promise<{start?: string}>}) {
  const lesson = await getLessonBySlug((await params).slug) as Lesson | null
  if (!lesson || !lesson.courses[0]) notFound()
  const course = lesson.courses[0]
  const flat = course.modules.flatMap((module, moduleIndex) => module.lessons.map((item, lessonIndex) => ({item, module, moduleIndex, lessonIndex})))
  const current = flat.findIndex(({item}) => item._id === lesson._id)
  const position = flat[current]
  const previous = flat[current - 1]?.item
  const next = flat[current + 1]?.item
  const embed = new URL(lesson.videoUrl).searchParams.get('v')
  const startSeconds = Math.max(0, Math.floor(Number((await searchParams).start) || 0))
  return <main className="lesson-page"><AnalyticsView event={{name: 'lesson_viewed', properties: {lesson_slug: lesson.slug.current, course_slug: course.slug.current, module_number: position.moduleIndex + 1, lesson_number: position.lessonIndex + 1, duration_seconds: lesson.duration, has_resume_position: false}}} /><div className="lesson-canvas"><header className="lesson-header"><Link className="lesson-brand" href="/"><span className="lesson-logo">▼</span><span>Vertex</span></Link><nav><Link href="/">Courses</Link><Link href="/my-learning">My Learning</Link></nav><div className="lesson-actions"><button aria-label="Notifications"><Icon name="bell" /></button><Show when="signed-in"><UserButton /></Show></div></header><div className="lesson-layout">
    <aside className="lesson-sidebar"><Link className="back-course" href={`/courses/${course.slug.current}`}>← <span>Back to course</span></Link><div className="sidebar-course"><div className="sidebar-mark">N</div><div><strong>{course.title}</strong><small>35% complete</small><i><b /></i></div></div><div className="sidebar-module-label">Module {position.moduleIndex + 1} of {course.modules.length}<span>⌄</span></div><div className="sidebar-lessons">{course.modules.map((module, moduleIndex) => <div className={`sidebar-module ${moduleIndex === position.moduleIndex ? 'current' : ''}`} key={module._key}><div className="sidebar-module-row"><span className="sidebar-number">{moduleIndex + 1}</span><div><strong>{module.title}</strong><small>{duration(module.lessons.reduce((sum, item) => sum + (item.duration ?? 0), 0))}</small></div><span className="sidebar-chevron">{moduleIndex === position.moduleIndex ? '⌃' : '⌄'}</span></div>{moduleIndex === position.moduleIndex && <div className="sidebar-module-lessons">{module.lessons.map((item, lessonIndex) => <Link className={item._id === lesson._id ? 'selected' : ''} href={`/lessons/${item.slug.current}`} key={item._id}><span>{lessonIndex === 0 ? '•' : '○'}</span><span>{item.title}<small>{duration(item.duration ?? 0)}</small>{item._id === lesson._id && <em>Now playing</em>}</span>{item._id === lesson._id && <b>▶</b>}</Link>)}</div>}</div>)}</div></aside>
    <article className="lesson-main"><div className="lesson-breadcrumb"><Link href="/">All Courses</Link><span>›</span><Link href={`/courses/${course.slug.current}`}>{course.title}</Link><span>›</span><span>{position.module.title}</span><span>›</span><span>{lesson.title}</span></div><div className="lesson-title-row"><div><span className="lesson-badge">LESSON {position.moduleIndex + 1}.{position.lessonIndex + 1}</span><h1>{lesson.title}</h1><p>Learn how {course.title} handles {lesson.title.toLowerCase()} in both Server and Client Components.</p></div><LessonBookmark /></div><div className="lesson-meta"><span><Icon name="clock" />{duration(lesson.duration)}</span><span><Icon name="level" />{course.level[0].toUpperCase() + course.level.slice(1)}</span><span><Icon name="users" />{lesson.studentCount.toLocaleString()} students</span></div><div className="video-frame"><LessonVideo videoId={embed ?? ''} lessonSlug={lesson.slug.current} courseSlug={course.slug.current} durationSeconds={lesson.duration} startSeconds={startSeconds} /></div><LessonTabs lessonSlug={lesson.slug.current} courseSlug={course.slug.current} notes={<PortableText value={lesson.notes as never} />}><section className="lesson-overview"><h2>Overview</h2><PortableText value={lesson.notes as never} /><hr /><h3>In this lesson you will:</h3><ul>{(lesson.keyPoints ?? []).map((point) => <li key={point}><Icon name="check" />{point}</li>)}</ul>{lesson.proTip && <div className="pro-tip"><span>♧</span><div><strong>Pro Tip</strong><p>{lesson.proTip}</p></div></div>}<h2 className="resources-heading">Resources</h2><div className="resources-grid">{(lesson.resources ?? []).map((resource) => <a href={resource.url} target="_blank" rel="noreferrer" key={resource._key}><strong>▧</strong><span><b>{resource.title}</b><small>{resource.description}</small></span><em>↗</em></a>)}</div></section></LessonTabs><div className="lesson-footer">{previous ? <Link href={`/lessons/${previous.slug.current}`}>← <span>Previous Lesson<small>{previous.title}</small></span></Link> : <span />}{next && <Link href={`/lessons/${next.slug.current}`}><span>Next Lesson<small>{next.title}</small></span> →</Link>}</div></article>
  </div></div></main>
}

export async function generateMetadata({params}: {params: Promise<{slug: string}>}) {const lesson = await getLessonBySlug((await params).slug) as Lesson | null; return {title: lesson ? `${lesson.title} — Vertex` : 'Lesson — Vertex', description: lesson?.title}}
